server:
  port: 8082

spring:
  application:
    name: transaction-category-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_category_db
    username: "postgres"
    password: "2213"
  jpa:
    generate-ddl: false
