server:
  port: 8083

spring:
  application:
    name: transaction-category-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_category_db
    username: "postgres"
    password: "2213"
  jpa:
    generate-ddl: false

logging:
  level:
    br.com.andredevel.transaction.category.service.api.config: DEBUG
    org.springframework.security: DEBUG
    ROOT: INFO